target "BigToeTimer" do
pod 'AFNetworking'
pod 'Qiniu', '~> 7.0'
pod 'ZXPAutoLayout'
pod 'BlocksKit'
pod 'RESideMenu', '~> 4.0.7'
pod 'SDWebImage'
pod 'SSKeychain'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'DateTools'
pod 'GPUImage'
pod 'Reachability'
pod 'GRMustache'
pod 'DTCoreText'
pod 'KRVideoPlayer'
pod 'UMengSocial'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'MJExtension'
pod 'tingyunApp'
pod 'PNChart'
pod 'DXPopover'
pod 'pop'
pod 'Canvas'
end
